import type { Row } from "./aggregate";
const pct = (x: unknown) => x === null ? "—" : (100*Number(x)).toFixed(2);
const table = (headers: string[], rows: unknown[][]) => [headers.join(" | "), headers.map(()=>"---").join(" | "), ...rows.map(r=>r.join(" | "))].join("\n");
export function survivalReport(rows: Row[]) {
  const get = (id: string, model="current") => rows.find(r=>r.scenario===id && r.model===model)!;
  const rate = (id: string, model="current") => pct(get(id,model).finalRate);
  const sections = ["# Survivability model experiment", "## WHAT QUESTION DID WE TEST?",
    "Does normalized formation Survivability plus weighted individual selection produce size-stable, composition-sensitive losses and different individual risks? This is evidence about the existing experiments, not a balance decision. No constants or game behavior were changed.",
    "The centerpiece has an important control: at exactly 100 troops, normalized Survival equals current total Survival. Consequently CURRENT and NORMALIZED have identical rate curves here; WEIGHTED and NORMALIZED + WEIGHTED have identical allocation behavior. The size experiment distinguishes normalization. Tables label theoretical rates versus sampled probabilities explicitly.",
    "## CORE COMPOSITION GRADIENT",
    "Theoretical loss %, identical for all four models at 100 troops. Columns are exact hostile/own Power ratios; weighting changes identities, never casualty totals.",
    table(["BM / SP","0.25×","0.5×","1×","1.5×","2×"], [100,75,50,25,0].map(b=>[`${b}/${100-b}`,...[.25,.5,1,1.5,2].map(p=>rate(`gradient-${b}-${p}`))])),
    "The curve is continuous and monotone across this gradient. Pure Bridgemen at 2× would reach 100% before the 95% final cap. The 3% base floor remains configured throughout, but does not bind at these pressure levels (base rates are 6.25–50%).",
    "## ARMY SIZE SCALING",
    "Even pressure. Each cell is theoretical loss % / sampled loss %. Normalized uses equal selection here; adding weighting preserves its casualty count.",
    table(["Composition","Troops","CURRENT","NORMALIZED"], [1,.5,0].flatMap(share=>[10,100,1000].map(n=>[share===1?"BM":share===0?"SP":"50/50",n,...["current","normalized"].map(m=>{const r=get(`size-${n}-${share}`,m);return `${pct(r.finalRate)} / ${r.casualtyPercent.toFixed(2)}`;})]))),
    "Normalized theoretical percentages are exactly invariant. Integer casualty counts still create individual-battle variation, especially in small armies; sampled means need not be exactly equal. Zero-Survival mixed armies are already size invariant under CURRENT. Pure large Bridgemen hit the cap, hiding further raw amplification.",
    "## CASUALTY DISTRIBUTION",
    "Even pressure, 100 troops; sampled percentages of starting units lost. Allocation columns compare CURRENT versus WEIGHTED; normalization is identical at this size.",
    table(["BM/SP","Equal BM loss %","Equal SP loss %","Weighted BM loss %","Weighted SP loss %","Weighted casualties that are BM %"],[75,50,25].map(b=>{const e=get(`gradient-${b}-1`),w=get(`gradient-${b}-1`,"weighted");return [`${b}/${100-b}`,pct(e.bridgeman_casualtyRate),pct(e.spearman_casualtyRate),pct(w.bridgeman_casualtyRate),pct(w.spearman_casualtyRate),pct(Number(w.bridgeman_averageCasualties)/w.averageCasualties)];})),
    "Weighted sampling concentrates losses on fragile troops, creating a real ablative-screen incentive. It is not a kill-first rule: durable troops still die. Weights are sampling priorities, not final probability ratios; depletion of fragile troops changes the remaining lottery.",
    "## SHARDBEARERS",
    "Each formation has 100 infantry plus exactly one Shardbearer. Sampled death probabilities; C = CURRENT, N = NORMALIZED, W = WEIGHTED, NW = both. Full data also includes per-infantry risks, total losses and standard errors.",
    table(["Infantry","Pressure","C Shard %","N Shard %","W Shard %","NW Shard %","NW BM %","NW SP %","NW total loss %"],[100,50,0].flatMap(b=>[.5,2].map(p=>{const id=`shard-${b}-${p}`,nw=get(id,"normalized-weighted");return [`${b}/${100-b}`,p,...["current","normalized","weighted","normalized-weighted"].map(m=>pct(get(id,m).shardDeathProbability)),pct(nw.bridgeman_casualtyRate),pct(nw.spearman_casualtyRate),nw.casualtyPercent.toFixed(2)];}))),
    "Every individual's weight is positive, so no unit is mathematically immortal. Low observed Shardbearer risk can nevertheless feel nearly immune. Sampling uncertainty matters: standard errors are in the data; a zero observed rate would only imply an approximate 95% upper bound of 3/replications, not immunity.",
    "## CHULLS",
    "50 BM + 50 SP, adding Chulls; even relative pressure. Chulls add no Power, so hostile Power also stays fixed. Rates are theoretical except individual death percentages.",
    table(["Added Chulls","CURRENT loss %","NORMALIZED loss %","NW BM %","NW SP %","NW Chull %"],[0,1,5,20,100].map(c=>{const id=`chull-${c}`,r=get(id,"normalized-weighted");return[c,rate(id),rate(id,"normalized"),pct(r.bridgeman_casualtyRate),pct(r.spearman_casualtyRate),pct(r.chull_casualtyRate)];})),
    "Adding Chulls smoothly reduces the formation casualty percentage here. Weighted Chulls are protected more than infantry, rather than absorbing more deaths themselves. Their contribution can shield other units through the rate stage even though they contribute no combat Power.",
    table(["Pure Chulls","Own / hostile Power","CURRENT loss %","NORMALIZED loss %"],[1,10,100].map(n=>[n,"0 / 10",rate(`chull-zero-power-${n}`),rate(`chull-zero-power-${n}`,"normalized")])),
    "Zero own Power with positive opposition uses the existing 80% base cap. These are fixed-opposition diagnostics, not proportional fights; the ratio is undefined. Pure Chulls cannot win against positive Power just because they survive. At one Chull, a normalized 26.67% rate means either zero or one death, not a fractional survivor.",
    "## FIELD SURGERY",
    "Even pressure. Theoretical loss percentages by rank 0 / I / II / III. Rank I and II give the same existing +1 Survival per Spearman; III gives +2. This plateau is source behavior, not simulation noise.",
    table(["BM share","Troops","CURRENT 0 / I / II / III","NORMALIZED 0 / I / II / III"],[0,.5,.25].flatMap(s=>(s===.25?[20,100,1000]:[10,100,1000]).map(n=>[s,n,...["current","normalized"].map(m=>[0,1,2,3].map(k=>rate(`surgery-${s}-${n}-${k}`,m)).join(" / "))]))),
    "25/75 cannot be represented exactly with ten troops: its small-army check uses twenty (5 BM / 15 SP). No composition rounding is hidden. Normalization makes research's percentage-point effect stable across proportional sizes, but not uniform across compositions. The full four-model data also captures Surgery's per-Spearman effect on selection weights.",
    "## MARGINAL UNIT EFFECTS",
    "Even relative pressure; theoretical normalized loss percentage and expected deaths. Holding relative pressure fixed intentionally removes the combat advantage from added Power. The fixed-hostile column restores that advantage against the original opponent Power.",
    table(["Formation","Power","Normalized loss %","Expected deaths","Fixed-hostile normalized loss %"],rows.filter(r=>r.category==="marginal"&&r.model==="normalized").map(r=>[r.army,r.power,pct(r.finalRate),r.expectedCasualties.toFixed(3),rate(r.scenario.replace("marginal-","fixed-"),"normalized")])),
    "One fragile troop worsens percentage resilience slightly; adding a durable troop improves it in these cases. Percent losses and absolute deaths are different: a lower percentage applied to more troops can still mean more deaths. Shardbearers also unlock existing support Power, so fixed-opposition results differ sharply from controlled relative pressure without implying a Survival discontinuity.",
    "## ANOMALIES / SURPRISES",
    "- The entire 100-troop gradient cannot distinguish normalization from CURRENT; it tests composition and selection only.\n- CURRENT size scaling is severe for pure compositions, but absent for zero-total-Survival 50/50 infantry.\n- Normalization assigns the same percentage resilience to a lone specialist and a thousand proportional specialists; small-battle outcomes remain discrete.\n- Weighting creates a strong fragile-screen incentive, not just a cosmetic distribution change.\n- Very durable rare units can have low practical risk without being mathematically immune.\n- Severe pressure depletes the fragile pool and increases durable-unit exposure; weight ratios do not translate directly into death-probability ratios.\n- The 95% rate cap masks the worst negative-Survival amplification and does not guarantee a surviving troop.\n- Field Surgery I and II are identical; there is no smooth improvement at every research rank.\n- Chulls lower loss rates without raising Power; survival must not be confused with positional victory.\n- Marginal Power changes, especially Shardbearer support, would confound Survival comparisons without controlled pressure.",
    "## METHOD AND REPRODUCTION",
    `This run contains ${new Set(rows.map(r=>r.scenario)).size} scenarios, ${rows.length} aggregate rows and ${rows.reduce((n,r)=>n+r.replications,0).toLocaleString("en-US")} seeded army evaluations. Ordinary rows use ${rows.find(r=>r.category==="gradient")!.replications} seeds; Shardbearer-containing rows use ${rows.find(r=>r.category==="shard")!.replications}. These are independent single engagements, not attrition campaigns.`,
    "Only CURRENT, NORMALIZED, WEIGHTED and NORMALIZED + WEIGHTED are included. All retain floor 0.03, base factor 0.25, maximum base 0.80, final cap 0.95, no optional Survival cap, and no Conclave effects. Normalized effective Survival = 100 × researched total Survival / troop count. Weighted selection uses w = exp(clamp(−ln(2) × researched singleton Survival, −20, 20)), then an exponential race −ln(U)/w sampled without replacement, preserving the exact casualty count. Default weights: BM 2, SP 0.5, Chull 0.25, Shardbearer 0.03125. Field Surgery I/II makes SP weight 0.25; III makes it 0.125.",
    "CURRENT calls the real applySurvivalLosses. Other variants use the existing isolated adapters without changing formulas. Each formation's researched effectivePower is multiplied by the specified ratio to supply exact scalar hostile Power; no fabricated opponent units or battle winner are inferred. All models share scenario/replication seeds. Aggregate per-unit probability means average deaths / starting count; casualty share means aggregate deaths of that type / aggregate total deaths.",
    "Run `npm run balance:survivability` (optional `-- --reps 1000 --rare-reps 10000`). [Full CSV](../../analysis/survivability-model/results.csv) includes every composition/pressure/model metric; [manifest](../../analysis/survivability-model/manifest.json) records source hashes, configuration and counts. Seeds start at zero; no seed-level bulk files are written. Sampled tables show two decimals, so very small differences may be rounding. No model is ranked or selected.",
  ];
  return sections.join("\n\n")+"\n";
}
