/** Lab-only experiment ported verbatim from combat-balance/models.ts at 45733e7.
 * Reference fixtures were generated by that harness before porting.
 * No production caller imports this module.
 */
import { applySurvivalLosses, casualtyRateAfterSurvivability, effectiveSurvivability, normalizeUnits, totalUnits, unitKeys, TIME_RULES, type UnitCounts } from "../convex/rules";
type Army = { units: UnitCounts; research: Record<string, number> };
/** Separate deterministic stream for the selection experiment, never for baseline. */
function random(seed: string) {
  let h = 2166136261;
  for (const c of seed) h = Math.imul(h ^ c.charCodeAt(0), 16777619);
  return () => {
    h = (h + 0x6d2b79f5) | 0;
    let t = Math.imul(h ^ (h >>> 15), h | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return (((t ^ (t >>> 14)) >>> 0) + 0.5) / 4294967296;
  };
}
export function casualtyWeight(
  army: Army,
  key: keyof UnitCounts,
  strength: number,
) {
  // Singleton effective Survival includes per-Spearman Field Surgery. It does not
  // misapply the whole army's Survival or a unit-role category to the individual.
  const individual = effectiveSurvivability({ [key]: 1 }, army.research, false);
  return Math.exp(Math.max(-20, Math.min(20, -strength * individual)));
}
export function weightedLosses(
  army: Army,
  count: number,
  seed: string,
  strength: number,
) {
  const roll = random(seed + ":weighted"),
    pool: { key: keyof UnitCounts; priority: number; index: number }[] = [];
  for (const key of unitKeys()) {
    const weight = casualtyWeight(army, key, strength);
    for (let i = 0; i < army.units[key]; i++)
      pool.push({
        key,
        priority: -Math.log(roll()) / weight,
        index: pool.length,
      });
  }
  // Exponential race = seeded weighted sampling without replacement. Every
  // individual has positive weight; lower Survival raises risk, not death priority.
  pool.sort((a, b) => a.priority - b.priority || a.index - b.index);
  const survivors = { ...army.units },
    casualties = normalizeUnits({});
  for (const entry of pool.slice(0, count)) {
    survivors[entry.key]--;
    casualties[entry.key]++;
  }
  return { survivors, casualties };
}

export function experimentalSurvivalLosses(units: UnitCounts, baseRate: number, seed: string, research: Record<string, number>) {
  const army = { units, research };
  const survival = effectiveSurvivability(units, research);
  const n = totalUnits(units);
  const effective = n ? 100 * survival / n : 0;
  const final = casualtyRateAfterSurvivability(baseRate, effective);
  // Same adapter as the harness: reuse production rounding, neutralize total Survival.
  const negativeMultiplier = 1 + Math.abs(Math.min(0, survival)) / TIME_RULES.statDiminishingConstant;
  const result = applySurvivalLosses(units, final / negativeMultiplier, seed, research, false, 0);
  return { ...result, baseCasualtyRate: baseRate,
    ...weightedLosses(army, totalUnits(result.casualties), seed, Math.log(2)) };
}

