import { test, expect } from "@playwright/test";
test("combat model is explicit, retained across presets/saves, and journal preserves historical model and unit losses",async({page})=>{
  const external:string[]=[];
  page.on("request",r=>{if(!r.url().startsWith("http://127.0.0.1:4186/"))external.push(r.url());});
  await page.goto("/");
  await expect(page.locator("#combatModel")).toHaveValue("current");
  await page.locator("#combatModel").selectOption("experimental-survival");
  await expect(page.locator("#combatModelStatus")).toContainText("Fixed 3% floor");
  await expect(page.locator("#casualty-minimum")).toBeDisabled();
  await page.locator("#preset").selectOption("Raid under attack");
  await page.locator("#reset").click();
  await expect(page.locator("#combatModel")).toHaveValue("experimental-survival");
  await page.locator("#resolve").click();
  await expect(page.locator("#log")).toContainText("[Experimental Survival]");
  await expect(page.locator("#log")).toContainText("Casualties:");
  await expect(page.locator("#log")).toContainText("lost/starting");
  await page.locator("#save").click();
  await page.locator("#combatModel").selectOption("current");
  await expect(page.locator("#log")).toContainText("[Experimental Survival]");
  await page.locator("#load").click();
  await expect(page.locator("#combatModel")).toHaveValue("experimental-survival");
  await page.locator("#combatModel").selectOption("current");
  await page.locator("#reset").click();
  await page.locator("#resolve").click();
  await expect(page.locator("#log")).toContainText("[Current]");
  await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem("conflict-lab")!);delete data.config.combatModel;localStorage.setItem("conflict-lab",JSON.stringify(data));});
  await page.locator("#load").click();
  await expect(page.locator("#combatModel")).toHaveValue("current");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(external).toEqual([]);
});
